version: "1.1"
stages:
- stage:
  - git-checkout:
      alias: repo
      params:
        depth: 1
- stage:
  - custom-script:
      alias: build
      commands:
      - cd ..
      - repo/build.sh
      namespaces:
      - filebeat-image
- stage:
  - release:
      alias: dicehub
      params:
        check_diceyml: false
        dice_yml: ${repo}/dice.yml
        release_id_path: dicehub
        replacement_images:
        - ${filebeat-image}
